[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.17"
auto_detect_solc = true
optimizer = true
optimizer_runs = 1000000
via_ir = true
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@erc3643/contracts/=lib/T-REX/contracts/",
  "@onchain-id/=lib/T-REX/node_modules/@onchain-id/",
  "T-REX/=lib/T-REX/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
  "eth-gas-reporter/=lib/T-REX/node_modules/eth-gas-reporter/",
  "forge-std/=lib/forge-std/src/",
  "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
  "hardhat/=lib/T-REX/node_modules/hardhat/",
  "ds-test/=lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
  "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
  "openzeppelin/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

[profile.openzeppelin]
libs = ["lib/openzeppelin-contracts"]
solc_version = "0.8.0"

[profile.openzeppelin-upgradeable]
libs = ["lib/openzeppelin-contracts-upgradeable"]
solc_version = "0.8.0"

[profile.trex]
solc_version = "0.8.17"
src = "lib/T-REX/"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
