name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Baixa todas as tags do Git para evitar conflitos

      - name: Configurar identidade do Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Instalar dependências
        run: npm install

      - name: Gerar nova versão com standard-version
        run: npm run release

      - name: Obter versão do package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Comitar mudanças no CHANGELOG e package.json
        run: |
          git add CHANGELOG.md package.json package-lock.json
          git commit -m "chore(release): $VERSION" || echo "Nada para commitar"
          git push origin main

      - name: Criar tag e enviar para o repositório
        run: |
          git tag $VERSION
          git push origin $VERSION

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
